[project]
name = "pyiri2016"
version = "1.2.2"
description = "International Reference Ionosphere 2016 for Python"
authors = [{name = "Ronald R. Ilma Campana", email = "ronald.ilmacampana@example.com"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy>=1.26.0,<2.0",
    "simple-settings>=1.2.0",
    "beautifulsoup4>=4.10.0",
    "wget>=3.2",
    "timeutil @ git+https://github.com/rilma/TimeUtilities.git",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=2.16.0",
    "coverage>=6.2",
    "parameterized>=0.8.1",
]

[build-system]
requires = ["setuptools>=60,<70", "numpy>=1.21.5,<2.0", "charset-normalizer>=2.0.0"]
build-backend = "setuptools.build_meta"

