[tool.poetry]
name = "pyiri2016"
version = "0.1.0"
description = "International Reference Ionosphere 2016 for Python"
authors = ["Ronald R. Ilma Campana <ronald.ilmacampana@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8.6,<3.11"
numpy = "^1.21.5"
simple-settings = "^1.2.0"
beautifulsoup4 = "^4.10.0"
wget = "^3.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.16.0"
coverage = "^6.2"
parameterized = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"